name: Deploy static dist/ to GitHub Pages
on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # (Optional) Fail fast if dist is missing or empty
      - name: Verify dist exists
        run: |
          test -d dist && test -f dist/index.html
          ls -al dist | head -n 50

      # Prevent Jekyll from ignoring files/folders
      - name: Add .nojekyll
        run: touch dist/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: upload
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
